### ISSUE TITLE
Validate new input/output token decimals

### ISSUE THREAD

**Issue by gonchs** [stablecoinswap/stablecoinswap-contracts#44]
Some tokens, such as [GUSD](https://etherscan.io/token/0x056Fd409E1d7A124BD7017459dFEa2F387b6d5Cd) have just 2 decimal points.

Please assert in `updateInputToken` and `updateOutputToken` that it's not possible to add tokens with decimals less than 2. This should be covered by tests.

Also adapt the tests to use 2 decimals (GUSD)  as the minimum instead of the current 6 decimals (USDC) we use. I want to make sure swaps, exchange rates and add/remove liquidity functions all work well when we work with 2-decimal tokens.

**Comment by esaulkov** [comment]
I've just found that `trade_fee` can be much more than `0.002` in some cases. For example:

Let's assume we have the same prices for all tokens (DAI, USDC, GUSD) - 1 USD. Then when user tries to swap he will receive different amount depending of output token:
```
1 DAI -> 0.997 USDC
1 DAI -> 0.99 GUSD
1 USDC -> 0.997 DAI
1 USDC -> 0.99 GUSD
1 GUSD -> 0.997 DAI
1 GUSD -> 0.997 USDC
```
For GUSD as output token we have `0.01` fee due small number of decimal points for this token. This additional amount doesn't increase `ownerFee`, just `tradeFee`. So for small amounts this fee could be up to `0.009` instead `0.002`.

**Comment by gonchs** [comment]
So the owner fee is still correct?

If yes, this is ok. We just need to let the user about this and document it.

How does this affect deposits and withdrawals?

Related:
- https://github.com/gonchs/stablecoinswap-x/issues/6#issuecomment-525577663
- https://github.com/stablecoinswap/stablecoinswap-contracts/commit/3f8b0d228ac61fb7d6a4faef41bba240bec8621e
- https://github.com/gonchs/stablecoinswap-frontend/issues/144

**Comment by esaulkov** [comment]
Owner fee is calculated in Stablecoinswap tokens (with 18 decimals), so it is the same as for DAI/USDC. This additional amount increases `poolSize`, so weight of one share increases.

For withdrawals we can't remove `0.01 GUSD`, so minimal amount to remove is `0.02` - with 50% fee. I guess we need to add this restriction to front-end.

Deposits should be ok, but I need to complete the tests to be sure.

**Comment by blimp666** [comment]
One more thought related to decimals: how it will affect the accuracy of ```tokenExchangeRateAfterFees``` and ```tokenOutputAmountAfterFees```? 
We use ```10 ** ERC20(input_token_address).decimals()``` as a multiplier in the first one and the same value as a divider in the last one. But if input token has only two decimals, it seems exchange rate will also have only two decimals. Am I right?
If yes, probably it would be good to use a constant instead of ```10 ** ERC20(input_token_address).decimals()```.

**Comment by esaulkov** [comment]
The result of `tokenExchangeRateAfterFees` is calculated in output tokens. So for equal prices and zero fees:
```
DAI -> GUSD: tokenExchangeRateAfterFees() = 100
GUSD -> DAI: tokenExchangeRateAfterFees() = 10**18
```

**Comment by blimp666** [comment]
>DAI -> GUSD: tokenExchangeRateAfterFees() = 100

So, if a real exchange rate is, for example, ```1.00452553```, we still get ```100```?

**Comment by esaulkov** [comment]
Yes

**Comment by blimp666** [comment]
I think we should change that. This rounding doesn't look an issue if user convents just 1 USD. But we apply this rate regardless to an amount, so, if you user wants to exchange 1000 tokens, in ```tokenOutputAmountAfterFees``` we still have ```1.00``` as the result of ```'self.tokenExchangeRateAfterFees(input_token_address, output_token_address) / 10 ** ERC20(input_token_address).decimals()``` (instead of ```1.00452553```). We have a rounding error up to 0.5% for any sum if token has two decimals.

**Comment by gonchs** [comment]
How do you propose to fix that?

**Comment by blimp666** [comment]
I think we could use a constant  ```10**N``` (10**18 or maybe 10**8) instead of ```10 ** ERC20(input_token_address).decimals()``` as it described here https://github.com/stablecoinswap/stablecoinswap-contracts/issues/45#issuecomment-525244045 .

**Comment by gonchs** [comment]
I was actually thinking the same thing. Let's change that as part of https://github.com/stablecoinswap/stablecoinswap-contracts/issues/45 after this issue is resolved.
