### ISSUE TITLE
Update event values

### ISSUE THREAD

**Issue by gonchs** [stablecoinswap/stablecoinswap-contracts#50]
To include more data about erc20 values and less about the sender (max are 3 values per event).

**Comment by blimp666** [comment]
It seems this issue affects https://github.com/gonchs/stablecoinswap-frontend/issues/152 . If we add erc20 values to events, then we could skip some requests at the frontend when an event received.
Should I postpone https://github.com/gonchs/stablecoinswap-frontend/issues/152 until this issue will be completed?

**Comment by gonchs** [comment]
How do you suggest we modify the events? Can you post the new suggested event definitions here as a comment?

**Comment by gonchs** [comment]
Also, if we remove the sender, will the events still be useful for the purpose of account balance updating?

**Comment by blimp666** [comment]
Actually, thinking more about that I'm not sure do we need  erc20 values in stablecoinswap events or not. On one hand in this case we could use these values directly from the event. But on the other hand all transactions have ```Transfer``` events from erc20 contracts, and the more additional data we store - the more gas we spend.

For example this one swap -  https://kovan.etherscan.io/tx/0xc602119830fa99587b26f5d70c039ed71d6be625453a273112ade0ccedb5c289#eventlog
There are three events: one ```Trade``` and two ```Transfer```. So, we can just get a transaction receipt - and we will have all erc20 values.
Or this one add liquidity https://kovan.etherscan.io/tx/0xbfedb12874ec7395a1746e4aa982493109f871fd97d5aedc635d14acb7b9f54b#eventlog 
we also have ```Transfer``` event there and we can get erc20 values from it.

As for the data about sender, probably we really could remove it - we just store ```msg.sender``` in liquidityAdded and liquidityRemoved events, but we always can get a sender from a transaction receipt.
