### ISSUE TITLE
Fixed price oracle

### ISSUE THREAD

**Issue by gonchs** [stablecoinswap/stablecoinswap-contracts#51]
Create a new oracle as a separate file called fixed_price_oracle with it's own tests.

It should work the same as the current one except:
- not possible to update prices
- DAI price should be pulled from ~~MakerDao~~ DyDx oracle
- all other tokens should be set to $1.00

DAI apprers to be the only stablecoin we currently support which sometimes has the peg off by as much as 2% which can remain as such for weeks. All other stablecoins appear to hold the $1 peg relatively well.

If we set DAI to a fixed price as well, it may create mid-term imbalance in our reserves and prevent further trades while the DAI remain off-peg.

Benefits of the fixed prices are:
- prevents hacks: there will no longer be the need for the price updating server
- more likely to be profitable as most pairs will always be buy-low-sell-high due to 1:1 exchange with a fee. Except DAI.
- save us about 1 ETH of gas costs per month

Downsides:
- possibly less trading volume due to prices being different relative to the current market 

After this PR is accepted, pease also deploy it to Kovan, update the docs and price oracle address in the main contract on Kovan and test it all together in frontend.

**Comment by blimp666** [comment]
>DAI price should be pulled from MakerDao oracle

Which oracle should we use? I found [medianizer](https://developer.makerdao.com/feeds/) , but it seems this oracle provides only ETH reference price for the Maker system ( [mainnet](https://etherscan.io/address/0x729D19f657BD0614b4985Cf1D82531c67569197B), [kovan](https://kovan.etherscan.io/address/0x9FfFE440258B79c5d6604001674A4722FfC0f7Bc), [source](https://github.com/makerdao/medianizer/blob/master/src/medianizer.sol)).  At the moment it returns a2297597187080000 in hex (186.96 DAI for 1 ETH if I understand that correctly). But it seems ETH price is not exactly what we need. 

 Is there any other oracle?  Or should we use two oracles (medianizer to get makerdao price in ETH and some other to convert it to USD)?

**Comment by gonchs** [comment]
Let's use DyDx's price oracle:

https://etherscan.io/address/0x787f552bdc17332c98aa360748884513e3cb401a#readContract

`g_priceInfo` function, `price` value

But assert that min price: 0.95, max price: 1.05

**Comment by blimp666** [comment]
Btw, we also will have to make changes at the frontend. In the current version it listens to ```UpdatePrice``` event, but after described changes we will not longer have it.

**Comment by blimp666** [comment]
Also it seems there is no DyDx's price oracle on Kovan, and we need to deploy an own instance to test it (maybe a simplified one because original DyDx's price oracle contract has 6 different contract addresses in the constructor parameters  and 1500 lines of code).

**Comment by gonchs** [comment]
Skip Kovan. Seems like way too much effort. Let's test it on the mainnet.

**Comment by blimp666** [comment]
We can skip deploying to Kovan, but I think we need a simplified dydx oracle contract (a kind of stub - just ```g_priceInfo``` and ```updatePrice``` functions) for pytest anyway. 
Actually I've almost implemented it. Now it almost works, tests for new fixed_price_oracle contract are green, but it uses uint256 data in ```g_priceInfo``` tuple for now. At the moment I'm trying to figure out how to handle uint128 and uint32 in new fixed_price_oracle contract (```g_priceInfo``` of original dydx oracle returns that, but vyper doesn't support it out of the box).

**Comment by gonchs** [comment]
If it's not possible to convert in Vyper, we can deploy a simple contract in Solidity which sole purpose would be to convert those values into something we can use in Vyper.

**Comment by blimp666** [comment]
New contract is deployed on mainnet at 0x31603e6212222255056c54D92f55586E471415BD and it seems to work with dydx oracle well. At least it returns correct price for DAI token and it returns ```10000000000000000000``` for USDC token (which is correct normalized token price). 
Also it is deployed on kovan at 0x2aeaA71BEBE1AcB1a308D8b9C5CB39c6E3b739FE .

**Comment by gonchs** [comment]
Let's deploy the merged version to Kovan and Mainnet.

**Comment by blimp666** [comment]
Deployed to Mainnet https://etherscan.io/address/0x06965ecf77f78a1fc5592fba168329d122f4f114
And to Kovan https://kovan.etherscan.io/address/0x97acc4ea80e0714CA72bB17C5928b45512d86471
Supported tokens are added and the code is verified at etherscan (for both contracts).
